import { RECT_ASSEMBLY_CODE, RECT_MACHINE_CODE } from './rect'
import { MAX_ASSEMBLY_CODE, MAX_MACHINE_CODE } from './max'
import { PONG_ASSEMBLY_CODE, PONG_MACHINE_CODE } from './pong'

export default {
  RECT_ASSEMBLY_CODE,
  RECT_MACHINE_CODE,
  MAX_ASSEMBLY_CODE,
  MAX_MACHINE_CODE,
  PONG_ASSEMBLY_CODE,
  PONG_MACHINE_CODE
}
